### ISSUE TITLE
[bug] containers still exist in containerd after pouch removing them

### ISSUE THREAD

**Issue by Letty5411** [alibaba/pouch#568] opened 2018-01-12 03:39 UTC
**Issue Description**
After running integration tests in pouch. There are legacy containers in containerd.
More info is here:
```
# ps -ef |grep containerd
root     10673  9726  0 11:33 ?        00:00:00 /usr/local/bin/containerd -c /etc/containerd/config.toml -a /var/run/containerd.sock --root /var/lib/pouch/containerd/root --state /var/lib/pouch/containerd/state -l info
root     10786  4068  0 11:35 pts/2    00:00:00 grep --color=auto containerd

# pouch ps -a
Name   ID   Status   Created   Image   Runtime

# ctr -a /var/run/containerd.sock containers ls
CONTAINER                                                           IMAGE    RUNTIME
06be9304abde8666cfccad8f59e2ed0cd52761798924e992f27c48f61e8c86a0    -        io.containerd.runtime.v1.linux
08500eabc7267427bf3762c84ae68d3e6eb7908b76bffdd04409a00eae5b6f6c    -        io.containerd.runtime.v1.linux
134967155540372f94ba06bcb709b4a6a510f76c347b4b4bc336d2cd667c25bd    -        io.containerd.runtime.v1.linux
1aa60e03ed9cf916800afcd36b5e69c9c11a0d2bc1d0feb2a657bc49eaadf5c8    -        io.containerd.runtime.v1.linux
485a59bcb7cd405c4aa617fcd7705b29056535d7be6954c0664784ac0236a4da    -        io.containerd.runtime.v1.linux
98f813042214c2781af41228cf7190596d8420e3d5519ec05f705a137d7268f1    -        io.containerd.runtime.v1.linux
c5cf9c359d35da319839191c97e420490dff7ddc5a61874ce37cf13044437c2f    -        io.containerd.runtime.v1.linux
df04797ed293e377d71d1c2e96378a78e471923d43e5aed98528bebd78af1c7b    -        io.containerd.runtime.v1.linux
f8c779e9aa12a8286d3120f298e620268ca98aad800e4748d9e451b4906848fb    -        io.containerd.runtime.v1.linux
fc38bc09413f424221f8dadd052df9574143bc736a952f5f2b0123297b045150    -        io.containerd.runtime.v1.linux
fee7fce99678771248161491fa972cb57253cec97aa26dffacd7b43e6d19acab    -        io.containerd.runtime.v1.linux
ff5feeff7accda33221d21e9dc485f0c342daa961e42f4127a82f6db31252ed1    -        io.containerd.runtime.v1.linux
```
**Describe what happened**:

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
```
# uname -a
Linux iZj6c8wfhczf614erpi8anZ 3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- pouch version (use `pouch version`):
```
# pouch version
Version:         0.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-01-12T11:15:02.252745858+08:00
GitCommit:
GoVersion:       go1.9.2
KernelVersion:
Os:              linux
```
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by skoo87** [comment] 2018-01-16 06:40
`root@ubuntu:/media/psf/Home/sk/src/github.com/alibaba/pouch# pouch rm -f 1efc40 ee767c 1c6ee5 cb2dff
1efc40
ee767c
1c6ee5
cb2dff
root@ubuntu:/media/psf/Home/sk/src/github.com/alibaba/pouch# ctr -a /var/run/containerd.sock containers ls
CONTAINER    IMAGE    RUNTIME
`

please clear the environment first, then test it. I can't reproduce it.  @Letty5411

**Comment by allencloud** [comment] 2018-07-26 17:42
I think this have been fixed. Closing it.

**Closed by allencloud** 2018-07-26 17:42 UTC
Labels: kind/bug
