### ISSUE TITLE
[flaky test] failure in cri-tools test: Container Mount Propagation

### ISSUE THREAD

**Issue by allencloud** [alibaba/pouch#2290] opened 2018-09-29 14:26 UTC
### Ⅰ. Issue Description

I found that in the cri-tools, we always met the flaky test 
```
• Failure [1.371 seconds]
[k8s.io] Container Mount Propagation
/home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:73
  runtime should support mount propagation
  /home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:45
    mount with 'rshared' should support propagation from host to container and vice versa [It]
    /home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:94
    len(output) should not be zero.
    Expected
        <int>: 0
    not to be zero-valued
    /home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container_linux.go:111
```

Could you help to take a look at this? @Starnop @YaoZengzeng 

### Ⅱ. Describe what happened
cri-tools fails.

### Ⅲ. Describe what you expected to happen
cri-tools passes.

### Ⅳ. How to reproduce it (as minimally and precisely as possible)

1.
2.
3.

### Ⅵ. Environment:

- pouch version (use `pouch version`): master code
- OS (e.g. from /etc/os-release): travis-ci
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by Starnop** [comment] 2018-09-30 01:58
At present, almost all flaky tests are caused by IO problem , and that's one of the it. :)

**Comment by Starnop** [comment] 2018-09-30 02:37
> I see. Could you file an issue to explicitly show the detailed plan for how to tackle the IO problems in the code base? @Starnop

@fuweid is leading the way, and a roadmap is needed which I'm looking forward to.

**Comment by allencloud** [comment] 2018-11-22 05:02
Can we close this now? @Starnop @fuweid 
I have not seen cri-tools failure for a long time. 😄

**Comment by fuweid** [comment] 2018-12-04 12:18
Since the IO issue is gone, we can close this.

**Closed by fuweid** 2018-12-04 12:18 UTC
Labels: areas/test, kind/bug
