### ISSUE TITLE
kube-proxy start failed when deploy k8s v1.12.0 (with kubeadm) + pouch 1.1.0

### ISSUE THREAD

**Issue by xwisen** [alibaba/pouch#2649] opened 2019-01-04 15:04 UTC
## Question
kube-proxy start failed when deploy k8s v1.12.0 + pouch 1.1.0
### os
```shell
[root@k8s-1 ~]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

```
### k8s
```shell
[root@k8s-1 ~]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4", GitCommit:"f49fa022dbe63faafd0da106ef7e05a29721d3f1", GitTreeState:"clean", BuildDate:"2018-12-14T07:06:49Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
[root@k8s-1 ~]# kubelet --version
Kubernetes v1.12.4

```
### pouch
```shell
[root@k8s-1 ~]# pouch version
KernelVersion:   3.10.0-957.1.3.el7.x86_64
Os:              linux
Version:         1.1.0
APIVersion:      1.24
Arch:            amd64
BuildTime:       2018-12-24T10:07:01+00:00
GitCommit:       1.1.0
GoVersion:       go1.10.4

```
### kube-proxy daemonset yaml
```yaml
[root@k8s-1 ~]# kubectl -n kube-system get daemonset kube-proxy -o yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  creationTimestamp: 2019-01-04T10:03:50Z
  generation: 1
  labels:
    k8s-app: kube-proxy
  name: kube-proxy
  namespace: kube-system
  resourceVersion: "1218"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/daemonsets/kube-proxy
  uid: 08c5be85-1008-11e9-8fd9-080027d3613a
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: kube-proxy
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      creationTimestamp: null
      labels:
        k8s-app: kube-proxy
    spec:
      containers:
      - command:
        - /usr/local/bin/kube-proxy
        - --config=/var/lib/kube-proxy/config.conf
        image: k8s.gcr.io/kube-proxy:v1.12.0
        imagePullPolicy: IfNotPresent
        name: kube-proxy
        resources: {}
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
      dnsPolicy: ClusterFirst
      hostNetwork: true
      priorityClassName: system-node-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: kube-proxy
      serviceAccountName: kube-proxy
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-proxy
        name: kube-proxy
      - hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
        name: xtables-lock
      - hostPath:
          path: /lib/modules
          type: ""
        name: lib-modules
  templateGeneration: 1
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
status:
  currentNumberScheduled: 1
  desiredNumberScheduled: 1
  numberMisscheduled: 0
  numberReady: 0
  numberUnavailable: 1
  observedGeneration: 1
  updatedNumberScheduled: 1

```
### kube-proxy container error info
```shell
[root@k8s-1 ~]# docker  ps -a | grep kube-proxy
k8s_kube-proxy_kube-proxy-qhgxq_kube-system_0bf6caeb-1008-11e9-8fd9-080027d3613a_2                         ea0c5c   Exited (255) 4 minutes   4 minutes ago    k8s.gcr.io/kube-proxy:v1.12.0                                         runc
k8s_POD_kube-proxy-qhgxq_kube-system_0bf6caeb-1008-11e9-8fd9-080027d3613a_1                                4c4749   Up 24 minutes            24 minutes ago   registry.cn-hangzhou.aliyuncs.com/google-containers/pause-amd64:3.0   runc
[root@k8s-1 ~]# docker  logs k8s_kube-proxy_kube-proxy-qhgxq_kube-system_0bf6caeb-1008-11e9-8fd9-080027d3613a_2
W0104 14:59:29.155654       1 proxier.go:458] Failed to load kernel module ip_vs_rr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0104 14:59:29.157777       1 proxier.go:458] Failed to load kernel module ip_vs_wrr with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0104 14:59:29.158472       1 proxier.go:458] Failed to load kernel module ip_vs_sh with modprobe. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
W0104 14:59:29.162873       1 server_others.go:295] Flag proxy-mode="" unknown, assuming iptables proxy
I0104 14:59:29.182249       1 server_others.go:148] Using iptables Proxier.
F0104 14:59:29.182290       1 server.go:360] unable to create proxier: can't set sysctl net/ipv4/conf/all/route_localnet: open /proc/sys/net/ipv4/conf/all/route_localnet: read-only file system
```

**Comment by xiaoxubeii** [comment] 2019-01-05 04:14
The problem is `/proc/sys/*` are mounted as readonly paths:
```
defaultReadonlyPaths = []string{
		"/proc/asound",
		"/proc/bus",
		"/proc/fs",
		"/proc/irq",
		"/proc/sys",
		"/proc/sysrq-trigger",
	}
``` 
even when the pod is privileged. It has been fixed in kubelet dockershim #68803 but not in cri runtime. I will follow Kubernetes and create a pr if necessary.

**Comment by xwisen** [comment] 2019-01-06 05:37
container can't mout /proc, so this problem can't be solved in handmode:
```shell
1月 06 00:33:30 k8s-1 pouchd[2944]: time="2019-01-06T00:33:30.672764677-05:00" level=error msg="failed to start container: "e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd", failed to start container "e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd": failed to create container(e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd) on containerd: failed to create task for container(e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd): OCI runtime create failed: container_linux.go:265: starting container process caused "process_linux.go:348: container init caused \"rootfs_linux.go:57: mounting \\\"/proc\\\" to rootfs \\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd/rootfs\\\" at \\\"/proc\\\" caused \\\"\\\\\\\"/var/lib/pouch/containerd/state/io.containerd.runtime.v1.linux/default/e6c2df07856712c6f1b7b4373384dffe497a97c9d1581a1e30b860bf9ca908bd/rootfs/proc\\\\\\\" cannot be mounted because it is located inside \\\\\\\"/proc\\\\\\\"\\\"\"": unknown"
```

**Comment by xiaoxubeii** [comment] 2019-01-07 10:48
@xwisen No you can't mount /proc/* manually because it is already mounted as readonly.

**Comment by xiaoxubeii** [comment] 2019-01-09 03:30
I have created #72708 to track, so we can determine in which side we should fix the bug.

**Closed** 2019-02-26 08:11 UTC
Labels: areas/kubernetes
