### ISSUE TITLE
[compatiblity problem] start pouchd with the newest code failed 

### ISSUE THREAD

**Issue by HusterWan** [alibaba/pouch#296] opened 2017-12-12 14:15 UTC
**Issue Description**
```
ERRO[2017-12-12 21:58:58.493778055] failed to wait process: /usr/local/bin/containerd, signal: killed
WARN[2017-12-12 21:58:58.493832831] process: /usr/local/bin/containerd exited
Error: failed to decode meta data: json: cannot unmarshal number into Go struct field ContainerInfo.Status of type types.Status
ERRO[2017-12-12 21:58:58.493859940] failed to decode meta data: json: cannot unmarshal number into Go struct field ContainerInfo.Status of type types.Status
```
**Describe what happened**:
ContainerInfo.Status is int before, now is string, compatiblity problem

**Describe what you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1.
2.
3.

**Anything else we need to know?**:

**Environment**:
- pouch version (use `pouch version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by allencloud** [comment] 2017-12-12 16:30
It is caused by pr https://github.com/alibaba/pouch/pull/286. And the reason and solution are both in comments of it.

> After merging this, meta store object has changed format. So if /var/lib/pouch has legacy data, When we start pouchd from this commit. So we need to remove data in /var/lib/pouch.

**Comment by allencloud** [comment] 2017-12-12 16:30
Closing this, and feel free to tell us if we miss something.

**Closed by allencloud** 2017-12-12 16:30 UTC
